services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8813:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    entrypoint: >
      bash -c "
        apt-get update &&
        apt-get install -y docker.io maven &&
        usermod -aG docker jenkins &&
        exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "
volumes:
  jenkins_home:
    driver: local