spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/review_sharded?useSSL=true&serverTimezone=UTC
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: prod-mq-server
    port: 5672
    username: prod_user
    password: prod_password
    virtual-host: /prod