spring:
  datasource:
    url: jdbc:mysql://localhost:3307/review_sharded?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    virtual-host: /test