# Swagger/OpenAPI 配置
springdoc:
  # API文档路径
  api-docs:
    path: /v3/api-docs
    enabled: true
  
  # Swagger UI配置
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # 默认展开所有标签
    tags-sorter: alpha
    # 默认展开所有操作
    operations-sorter: alpha
    # 显示请求持续时间
    display-request-duration: true
    # 显示操作ID
    display-operation-id: true
    # 默认模型展开深度
    default-models-expand-depth: 2
    # 默认模型渲染
    default-model-rendering: model
    # 尝试它按钮默认展开
    try-it-out-enabled: true
  
  # 包扫描路径
  packages-to-scan: lhl.hana.xk.review_multi.controller
  
  # 路径匹配
  paths-to-match: /**
  
  # 显示actuator端点
  show-actuator: false
  
  # 缓存禁用（开发环境）
  cache:
    disabled: true